E-Commerce_App/Controllers/ActorsController.cs
using E_Commerce_App.Models;
using E_Commerce_App.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace E_Commerce_App.Controllers
{
    public class ActorsController : Controller
    {
        private readonly IActorRepository ActorRepository;

        public ActorsController(IActorRepository ActorRepository)
        {
            this.ActorRepository = ActorRepository;
        }

        public async Task<IActionResult> Index()
        {
            var allActors = await ActorRepository.GetAllAsync();
            return View(allActors);
        }
        [HttpGet]
        public IActionResult New()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> New(Actor actor)
        {
            if(ModelState.IsValid)
            {
                await ActorRepository.AddAsync(actor);
                return RedirectToAction("Index");
            }
            return View(actor);
        }

        public async Task<IActionResult> Details(int id)
        {
            Actor actor = await ActorRepository.GetByIdAsync(id);
            if(actor != null)
            {
                return View(actor);
            }
            return View("NotFound");
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            Actor actor = await ActorRepository.GetByIdAsync(id);
            if (actor != null)
            {
                return View(actor);
            }
            return View("NotFound");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id , Actor newactor)
        {
            if(ModelState.IsValid)
            {
               await ActorRepository.UpdateAsync(id,newactor);
                return RedirectToAction("Index");
            }
            return View(newactor);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            Actor actor = await ActorRepository.GetByIdAsync(id);
            if (actor != null)
            {
                return View("Delete", actor);
            }
            return View("NotFound");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id , Actor delactor)
        {
            Actor actor = await ActorRepository.GetByIdAsync(id);
            if(actor != null)
            {
                await ActorRepository.DeleteAsync(id);
                return RedirectToAction("Index");
            }
            return View("NotFound");
        }
        
    }
}

E-Commerce_App/Controllers/CinemasController.cs
using E_Commerce_App.Models;
using E_Commerce_App.Repository;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace E_Commerce_App.Controllers
{
    public class CinemasController : Controller
    {
        private readonly ICinemaRepository CinemaRepository;

        public CinemasController(ICinemaRepository CinemaRepository)
        {
            this.CinemaRepository = CinemaRepository;
        }
        public async Task<IActionResult> Index()
        {
            var allCinemas = await CinemaRepository.GetAllAsync();
            return View(allCinemas);
        }

        public async Task<IActionResult> Details(int id)
        {
            Cinema cinema = await CinemaRepository.GetByIdAsync(id);
            if (cinema != null)
            {
                return View(cinema);
            }
            return View("NotFound");
        }

        [HttpGet]
        public IActionResult New()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> New(Cinema cinema)
        {
            if(ModelState.IsValid)
            {
                await CinemaRepository.AddAsync(cinema);
                return RedirectToAction("Index");
            }
            return View(cinema);
        }

        [HttpGet]

        public async Task<IActionResult> Edit(int id)
        {
            Cinema cinema = await CinemaRepository.GetByIdAsync(id);
            if(cinema != null)
            {
                return View(cinema);
            }
            return View("NotFound");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit(int id , Cinema cinema)
        {
            if(ModelState.IsValid)
            {
                await CinemaRepository.UpdateAsync(id, cinema);
                return RedirectToAction("Index");
            }
            return View(cinema);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            Cinema cinema = await CinemaRepository.GetByIdAsync(id);
            if (cinema != null)
            {
                return View(cinema);
            }
            return View("NotFound");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Delete(int id, Cinema cinema)
        {
            if (ModelState.IsValid)
            {
                await CinemaRepository.DeleteAsync(id);
                return RedirectToAction("Index");
            }
            return View(cinema);
        }




    }
}

E-Commerce_App/Controllers/MoviesController.cs
using E_Commerce_App.Models;
using E_Commerce_App.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace E_Commerce_App.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieRepository MovieRepository;

        public MoviesController(IMovieRepository MovieRepository)
        {
            this.MovieRepository = MovieRepository;
        }
        public async Task<IActionResult> Index()
        {
            var allMovies = await MovieRepository.GetAllAsync(m => m.Cinema);
            return View(allMovies);
        }

        public async Task<IActionResult> Filter(string searchString)
        {
            var allMovies = await MovieRepository.GetAllAsync(m => m.Cinema);

            if (!string.IsNullOrEmpty(searchString))
            {
                var filtered = allMovies.Where(m => m.Name.Contains(searchString) || m.Description.Contains(searchString)).ToList();
                return View("Index" , filtered);
            }
            return View("Index", allMovies);
        }

        public async Task<IActionResult> Details(int id)
        {
            Movie movie = await MovieRepository.GetMovieByIdAsync(id);
            if(movie != null)
            {
                return View(movie);
            }
            return View("Not Found");
        }
        [HttpGet]
        public async Task<IActionResult> New()
        {
            var movieLists = await MovieRepository.GetMovieDropDownValues();
            ViewBag.Cinemas = new SelectList(movieLists.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieLists.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieLists.Actors, "Id", "FullName");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> New(MovieVM movie)
        {
            if (ModelState.IsValid)
            {
                await MovieRepository.AddMovieAsync(movie);
                return RedirectToAction("Index");
            }
            return View(movie);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            Movie movieData = await MovieRepository.GetMovieByIdAsync(id);

            if (movieData == null) return View("NotFound");

            var movieVM = new MovieVM()
            {
                Id = movieData.Id,
                Name = movieData.Name,
                Description = movieData.Description,
                ImageURL = movieData.ImageURL,
                MovieCategory = movieData.MovieCategory,
                CinemaId = movieData.CinemaId,
                ProducerId = movieData.ProducerId,
                Price = movieData.Price,
                StartDate = movieData.StartDate,
                EndDate = movieData.EndDate,
                ActorIds = movieData.Actors_Movies.Select(am => am.ActorId).ToList(),
                
            };

            var movieLists = await MovieRepository.GetMovieDropDownValues();
            ViewBag.Cinemas = new SelectList(movieLists.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieLists.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieLists.Actors, "Id", "FullName");

            return View(movieVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id , MovieVM movie)
        {
            if (ModelState.IsValid)
            {
                await MovieRepository.UpdateMovieAsync(movie);
                return RedirectToAction("Index");
            }
            return View(movie);
        }
    }
}

E-Commerce_App/Views/Movies/Details.cshtml
@model Movie
@{
    ViewData["Title"] = "Movie Details";
}

<div class="row">
   
    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-success">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.Name
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@Model.ImageURL" width="100%" alt="@Model.Name">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">@Model.Description</p>

                        <p class="card-text">
                            <b>Cinema: </b>
                            <a asp-action="Details" asp-controller="Cinemas" asp-route-id="@Model.Id">@Model.Cinema.Name</a>
                        </p>

                        <p class="card-text">
                            <b>Producer: </b>
                            <a asp-action="Details" asp-controller="Producers" asp-route-id="@Model.Id">@Model.Producer.FullName</a>
                        </p>
                        <p class="card-text"><b>Category: </b>@Model.MovieCategory</p>
                        <p class="card-text"><b>Start Date: </b>@Model.StartDate.ToString("dd MMM yy")</p>
                        <p class="card-text"><b>End Date: </b>@Model.EndDate.ToString("dd MMM yy")</p>
                        <p class="card-text ">
                            <b>Status: </b>
                            @if (DateTime.Now >= Model.StartDate && DateTime.Now <= Model.EndDate)
                            {
                                <span class="badge bg-success text-white">AVAILABLE</span>
                            }
                            else if (DateTime.Now > Model.EndDate)
                            {
                                <span class="badge bg-danger text-white">EXPIRED</span>
                            }
                            else
                            {
                                <span class="badge bg-primary text-white">UPCOMING</span>
                            }
                        </p>

                        <p class="card-text">
                            <b>Actors: </b>
                            <hr />
                            <div class="row">
                                @foreach(var actor in Model.Actors_Movies)
                                {
                                    <div class="col-md-3 text-center ">
                                        <img class="border-info rounded-circle" src="@actor.Actor.ProfilePictureURL" style="max-width : 100px"/>
                                        <br/>
                                        <a asp-controller="Actors" asp-action="Details" asp-route-id = "@actor.Actor.Id">@actor.Actor.FullName</a>
                                    </div>
                                }
                            </div>
                        </p>

                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer ">
                        <p class="card-text">
                            <a class="btn btn-outline-primary float-end" asp-action="Index" asp-route-id="@Model.Id">
                                Back To List
                            </a>
                            <a class="btn btn-success text-white @((DateTime.Now > Model.EndDate) ? "disabled" : "")" asp-controller="Orders" asp-action="AddToShoppingCart" asp-route-id="@Model.Id">
                                <i class="bi bi-cart-plus"></i> Add to Cart (Price @Model.Price.ToString("c"))
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</div>

E-Commerce_App/Views/Movies/Edit.cshtml
@model MovieVM
@using E_Commerce_App.Data.Enums
@{
    ViewData["Title"] = "Update Movie";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Update Movie</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit">
                    <div asp-validation-summary="All" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="label-control"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="StartDate" class="label-control"></label>
                                <input asp-for="StartDate" type="date" class="form-control" />
                                <span asp-validation-for="StartDate" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="EndDate" class="label-control"></label>
                                <input asp-for="EndDate" type="date" class="form-control" />
                                <span asp-validation-for="EndDate" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="Price" class="label-control"></label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="ImageURL" class="label-control"></label>
                                <input asp-for="ImageURL" class="form-control" />
                                <span asp-validation-for="ImageURL" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">

                            <div class="form-group">
                                <label asp-for="CinemaId" class="label-control"></label>
                                <select asp-for="CinemaId" class="form-control" asp-items="ViewBag.Cinemas"></select>
                                <span asp-validation-for="CinemaId" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="MovieCategory" class="label-control"></label>
                                <select asp-for="MovieCategory" class="form-control" asp-items="Html.GetEnumSelectList<MovieCategory>()"></select>
                                <span asp-validation-for="MovieCategory" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="ProducerId" class="label-control"></label>
                                <select asp-for="ProducerId" class="form-control" asp-items="ViewBag.Producers"></select>
                                <span asp-validation-for="ProducerId" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="ActorIds" class="label-control"></label>
                                <select asp-for="ActorIds" class="form-control" multiple asp-items="ViewBag.Actors"></select>
                                <span asp-validation-for="ActorIds" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="label-control"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 offset-4 texr-center">
                        <img width="100%" id="ImageURLPreview" style="margin-top: 5px" />
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-end"/>
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>

        </div>

    </div>
</div>

@section Scripts{
    <script>

        $(document).ready(function () {
            var output = document.getElementById("ImageURLPreview");
            output.src = $("#ImageURL").val();
        })

        $("#ImageURL").on("change", function () {
            var output = document.getElementById("ImageURLPreview")
            output.src = $(this).val()
        })
    </script>

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

E-Commerce_App/Views/Movies/Index.cshtml
@model List<Movie>
@{
    ViewData["Title"] = "Index";
}

<div class="row">
    @foreach(var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-success">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Name
                                    @if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {
                                        <a asp-controller="Movies" asp-action="Edit" asp-route-id="@item.Id" class="text-white float-end"><i class="bi bi-pencil-square"></i></a>
                                    }
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.ImageURL" width="100%" alt="@item.Name">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@item.Description</p>
                            <p class="card-text"><b>Cinema: </b>@item.Cinema.Name</p>
                            <p class="card-text"><b>Category: </b>@item.MovieCategory</p>
                            <p class="card-text"><b>Start Date: </b>@item.StartDate.ToString("dd MMM yy")</p>
                            <p class="card-text"><b>End Date: </b>@item.EndDate.ToString("dd MMM yy")</p>
                            <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                                {
                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                }
                                else if (DateTime.Now > item.EndDate)
                                {
                                    <span class="badge bg-danger text-white">EXPIRED</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">UPCOMING</span>
                                }
                            </p>

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-action="Details" asp-route-id = "@item.Id">
                                    <i class="bi bi-eye-fill"></i> Show Details
                                </a>
                                <a class="btn btn-success text-white @((DateTime.Now > item.EndDate) ? "disabled" : "")" asp-controller="Orders" asp-action="AddToShoppingCart" asp-route-id="@item.Id">
                                    <i class="bi bi-cart-plus"></i> Add to Cart (Price @item.Price.ToString("c"))
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

<partial name="_NewButton"/>

E-Commerce_App/Views/Movies/New.cshtml
@model MovieVM
@using E_Commerce_App.Data.Enums
@{
    ViewData["Title"] = "Create a new movie";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Create a new movie</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="New">
                    <div asp-validation-summary="All" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="label-control"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="StartDate" class="label-control"></label>
                                <input asp-for="StartDate" type="date" class="form-control" />
                                <span asp-validation-for="StartDate" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="EndDate" class="label-control"></label>
                                <input asp-for="EndDate" type="date" class="form-control" />
                                <span asp-validation-for="EndDate" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="Price" class="label-control"></label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="ImageURL" class="label-control"></label>
                                <input asp-for="ImageURL" class="form-control" />
                                <span asp-validation-for="ImageURL" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">

                            <div class="form-group">
                                <label asp-for="CinemaId" class="label-control"></label>
                                <select asp-for="CinemaId" class="form-control" asp-items="ViewBag.Cinemas"></select>
                                <span asp-validation-for="CinemaId" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="MovieCategory" class="label-control"></label>
                                <select asp-for="MovieCategory" class="form-control" asp-items="Html.GetEnumSelectList<MovieCategory>()"></select>
                                <span asp-validation-for="MovieCategory" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="ProducerId" class="label-control"></label>
                                <select asp-for="ProducerId" class="form-control" asp-items="ViewBag.Producers"></select>
                                <span asp-validation-for="ProducerId" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="ActorIds" class="label-control"></label>
                                <select asp-for="ActorIds" class="form-control" multiple asp-items="ViewBag.Actors"></select>
                                <span asp-validation-for="ActorIds" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="label-control"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 offset-4 texr-center">
                        <img width="100%" id="ImageURLPreview" />
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-end"/>
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>

        </div>

    </div>
</div>

@section Scripts{
    <script>
        $("ImageURL").on("change" , function(){
            var output = document.getElementById("ImageURLPreview")
            output.src = $(this).val
        })
    </script>
}