E-Commerce_App/Models/Producer.cs
using E_Commerce_App.Data.Base;
using System.ComponentModel.DataAnnotations;

namespace E_Commerce_App.Models
{
    public class Producer : IEntityBase
    {
        public int Id { get; set; }

        public string ProfilePictureURL { get; set; }

        [StringLength(50, MinimumLength = 3, ErrorMessage = "The Name should be between 3 and 50")]
        public string FullName { get; set; }

        [StringLength(50, MinimumLength = 5, ErrorMessage = "The Name should be between 3 and 50")]
        public string Bio { get; set; }

        public List<Movie>? Movies { get; set; }
    }
}

E-Commerce_App/Controllers/ProducersController.cs
using E_Commerce_App.Models;
using E_Commerce_App.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace E_Commerce_App.Controllers
{
    public class ProducersController : Controller
    {
        private readonly IProducerRepository ProducerRepository;

        public ProducersController(IProducerRepository ProducerRepository)
        {
            this.ProducerRepository = ProducerRepository;
        }

        public async Task<IActionResult> Index()
        {
            var allProducers = await ProducerRepository.GetAllAsync();
            return View(allProducers);
        }

        public async Task<IActionResult> Details(int id)
        {
            Producer producer = await ProducerRepository.GetByIdAsync(id);
            if(producer != null)
            {
                return View(producer);
            }
            return View("NotFound");
        }
        [HttpGet]
        public IActionResult New()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> New(Producer producer)
        {
            if (ModelState.IsValid)
            {
                await ProducerRepository.AddAsync(producer);
                return RedirectToAction("Index");
            }
            return View(producer);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            Producer producer = await ProducerRepository.GetByIdAsync(id);
            if (producer != null)
            {
                return View(producer);
            }
            return View("NotFound");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit(int id , Producer producer)
        {
            if(ModelState.IsValid)
            {
                await ProducerRepository.UpdateAsync(id , producer);
                return RedirectToAction("Index");
            }
            return View(producer);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            Producer producer = await ProducerRepository.GetByIdAsync(id);
            if(producer != null)
            {
                return View(producer);
            }
            return View("NotFound");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id , Producer producer)
        {
            await ProducerRepository.DeleteAsync(id);
            return RedirectToAction("Index");
        }
    }
}

E-Commerce_App/Views/Producers/Delete.cshtml
@model E_Commerce_App.Models.Producer

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete Confirmation for @Model.FullName</h1>

<hr />
<div class="row">
    <div class="col-md-8 offset-2">
        <form asp-action="Delete">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group text-center">
                <img id="ProfilePicturePreview" class="border-info rounded-circle" style="max-width:150px" />
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ProfilePictureURL" class="control-label"></label>
                <input asp-for="ProfilePictureURL" class="form-control" readonly />
                <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" readonly />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Bio" class="control-label"></label>
                <input asp-for="Bio" class="form-control" readonly />
                <span asp-validation-for="Bio" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Confirm" class="btn btn-outline-danger float-end" />
                <a asp-action="Index" class="btn btn-outline-secondary">Show All</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {

    <script>
        $(document).ready(function () {
            var output = document.getElementById("ProfilePicturePreview");
            output.src = $("#ProfilePictureURL").val();
        })

    </script>

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

E-Commerce_App/Views/Producers/Details.cshtml
@model E_Commerce_App.Models.Producer

@{
    ViewData["Title"] = "Details";
}

<h1>Details for @Model.FullName</h1>

<div class="row">
    <div class="col-md-8 offset-2">
        <form asp-action="New">

            <div class="form-group text-center">
                <img id="ProfilePicturePreview" class="border-info rounded-circle" style="max-width:150px" />
            </div>
            <div class="form-group">
                <label asp-for="ProfilePictureURL" class="control-label" style="padding-bottom : 5px"></label>
                <input asp-for="ProfilePictureURL" class="form-control" readonly />
            </div>
            <br />
            <div class="form-group">
                <label asp-for="FullName" class="control-label" style="padding-bottom : 5px"></label>
                <input asp-for="FullName" class="form-control" readonly />
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Bio" class="control-label" style="padding-bottom : 5px"></label>
                <input asp-for="Bio" class="form-control" readonly />
            </div>
            <br />
            <div class="form-group">

                @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <a class="btn btn-outline-success float-end" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
                }
                
                <a asp-action="Index" class="btn btn-outline-secondary">Show All</a>
            </div>
        </form>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById("ProfilePicturePreview");
            output.src = $("#ProfilePictureURL").val();
        })
    </script>
}

E-Commerce_App/Views/Producers/Edit.cshtml
@model E_Commerce_App.Models.Producer

@{
    ViewData["Title"] = "Edit";
}

<h1>Update Actor</h1>

<hr />
<div class="row">
    <div class="col-md-8 offset-2">
        <form asp-action="Edit">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group text-center">
                <img id="ProfilePicturePreview" class="border-info rounded-circle" style="max-width:150px" />
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ProfilePictureURL" class="control-label"></label>
                <input asp-for="ProfilePictureURL" class="form-control" />
                <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Bio" class="control-label"></label>
                <input asp-for="Bio" class="form-control" />
                <span asp-validation-for="Bio" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-outline-success float-end" />
                <a asp-action="Index" class="btn btn-outline-secondary">Show All</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {

    <script>
        $(document).ready(function () {
            var output = document.getElementById("ProfilePicturePreview");
            output.src = $("#ProfilePictureURL").val();
        })


        $("#ProfilePictureURL").on("change", function () {
            var output = document.getElementById("ProfilePicturePreview");
            output.src = $(this).val();
        })
    </script>

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

E-Commerce_App/Views/Producers/Index.cshtml
@model List<Producer>
@{
    ViewData["Title"] = "Index";
}


<table class="table">
    <thead>
        <tr>
            <th>ProfilePicture</th>
            <th>FullName</th>
            <th>Bio</th>
            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                <th>Actions</th>
            }
           
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="align-middle">
                    <img src="@item.ProfilePictureURL" class="rounded-circle" alt="@item.FullName" style="max-width : 150px"></img>
                </td>
                <td class="align-middle">
                    @item.FullName
                </td>
                <td class="align-middle">
                    @item.Bio
                </td>

                @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <td class="align-middle">
                        <a class="btn btn-outline-primary" asp-controller="Producers" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Edit</a> |
                        <a class="btn btn-outline-info" asp-controller="Producers" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i>Details</a> |
                        <a class="btn btn-danger text-white" asp-controller="Producers" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>Delete</a>
                    </td>
                }
                
            </tr>
        }
    </tbody>
</table>

<partial name="_NewButton" />

E-Commerce_App/Views/Producers/New.cshtml
@model E_Commerce_App.Models.Producer

@{
    ViewData["Title"] = "New";
}

<h1>Add A New Producer</h1>

<hr />
<div class="row">
    <div class="col-md-8 offset-2">
        <form asp-action="New">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group text-center">
                <img id="ProfilePicturePreview" class="border-info rounded-circle" style="max-width:150px" />
            </div>
            <div class="form-group">
                <label asp-for="ProfilePictureURL" class="control-label" style="padding-bottom : 5px"></label>
                <input asp-for="ProfilePictureURL" class="form-control" />
                <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="FullName" class="control-label" style="padding-bottom : 5px"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="Bio" class="control-label" style="padding-bottom : 5px"></label>
                <input asp-for="Bio" class="form-control" />
                <span asp-validation-for="Bio" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-success float-end" />
                <a asp-action="Index" class="btn btn-outline-secondary">Show All</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            var output = document.getElementById("ProfilePicturePreview");
            output.src = $("#ProfilePictureURL").val();
        })


        $("#ProfilePictureURL").on("change", function () {
            var output = document.getElementById("ProfilePicturePreview");
            output.src = $(this).val();
        })
    </script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}